version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - product-db

  product-db:
    image: postgres:13
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"


        -