spring:
    datasource:
        url: jdbc:postgresql://customer-db:5432/customerdb
        username: postgres
        password: postgres
    jpa:
        hibernate:
        ddl-auto: update
        show-sql: true