version: '3'
services:
  eureka-server:
    image: eurekaserver
    build: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  shipping-service:
    build: ./shipping-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server

  order-service:
    build: ./order-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
